# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

# Expose your documentation as YAML swagger compliant
app.swagger_yaml:
    path: /api/doc.yaml
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, format: yaml }

# Expose your documentation with Swagger UI
app.swagger_ui:
    path: /api/docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }