# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource:
        path: ../src/Presentation/Controller/
        namespace: App\Presentation\Controller
    type: attribute

# Import API documentation routes
app.swagger_ui:
    path: /api/docs
    controller: nelmio_api_doc.controller.swagger_ui

app.swagger:
    path: /api/doc.json
    controller: nelmio_api_doc.controller.swagger

app.swagger_yaml:
    path: /api/doc.yaml
    controller: nelmio_api_doc.controller.swagger
    defaults:
        format: yaml